name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    name: Build apk

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Run Android Lint
        run: ./gradlew lintDebug
      - name: Run Unit Test
        run: ./gradlew testDebug
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
