name: Android CI

on:
  push:

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'
          cache: 'gradle'
      - name: Run gradlew
        run: 
          chmod +x ./gradlew &&
          ./gradlew lintDebug &&
          ./gradlew testDebug &&
          ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
